### ISSUE TITLE
基于小板训练大板上的AI疑问

### ISSUE THREAD

**Issue by liunian321** [initial-h/AlphaZero_Gomoku_MPI#1]
请问你是如何基于小棋盘训练大棋盘上的AI，我用你提供的11x11的用于15x15的训练报错。方法不对吗？

**Comment by initial-h** [comment]
你把11的模型放到transfer learning的文件夹下，把棋盘改成15x15的。然后调用这个模型
training_pipeline = TrainPipeline(init_model=None, transfer_model='transfer_model/best_policy.model')

**Comment by liunian321** [comment]
> 你把11的模型放到transfer learning的文件夹下，把棋盘改成15x15的。然后调用这个模型
> training_pipeline = TrainPipeline（init_model = None，transfer_model ='transfer_model / best_policy.model'）

试了一下，感觉效果不太好。如果能像AlphaGo那样输入棋谱练习或许要快很多很多。
说句题外话，现在我觉得AlphaGo那套可能只适合围棋这种下棋后不会立竿见影的，像五子棋，象棋之类的不太合适。

**Comment by initial-h** [comment]
即使是用transfer learning的方式训练大棋盘网络，也并不是换上就立竿见影的，只是说在训练的过程中会稍快一些，这和cv里训练图像识别加载预训练模型的原理类似。
如果想要通过监督学习先学习人类棋谱，也可以去找KGS之类的棋谱，预处理之后放在kifu_train文件夹下，就是你想要的AlphaGo的方式了。
关于算法，总体来讲alphazero的算法是树搜索加神经网络，对于棋类这种奖励稀疏和延迟的问题都是适用的，也就是围棋，五子棋，象棋这些都是有效的。像alphazero也在国际象棋和日本将棋上取得了目前最强的水平。但是每种棋类都有一些小trick需要去采坑，在实现过程中去发现并做一些细微但有效的调整，其次就是需要很大的算力去慢慢提升，这些都是必不可少的。

**Comment by luopeng69131** [comment]
Ok了！我看了另外一个问题想明白了，哈哈哈哈谢谢阿！
