### ISSUE TITLE
请问15x15 11x11 分别训练了多久啊？

### ISSUE THREAD

**Issue by zxa308078684** [initial-h/AlphaZero_Gomoku_MPI#10]

**Comment by initial-h** [comment]
11的训练了一个月左右，15的少于一个月有点效果就停掉了。

**Comment by zxa308078684** [comment]
那我这边是可以基于你15的模型继续训练吧

**Comment by initial-h** [comment]
可以的，不过建议把buffer填满再开始train网络，之前我是data大于五倍batch size就开始训。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/f9c40012a71bca55bfa4c6c77295ad0248ba4d90/train_mpi.py#L387

**Comment by zxa308078684** [comment]
懂了 谢谢
