### ISSUE TITLE
关于 τ 的疑问

### ISSUE THREAD

**Issue by tangbh** [initial-h/AlphaZero_Gomoku_MPI#12]
在alpha zero 的文档中说 搜索概率 π 被返回，与 N(1/τ)成正比，
而在您的程序中， τ 没有参与返回概率中，而只是在选取action的时候使用，那这个τ是不是就没有意义了？

            p = softmax(1.0 / 1.0 * np.log(np.array(visits) + 1e-10))
            move_probs[list(acts)] = p
            # return the prob with temp=1
       
         return move,move_probs

**Comment by tangbh** [comment]
我看了Junxiao Song实现的程序中  ，是把  τ  参与到概率的计算中并返回到self-play的数据中

**Comment by initial-h** [comment]
我记得我也是这么做的，前面n步tau=1,后面的tau接近0.

**Comment by tangbh** [comment]
Junxiao Song的程序：
        # calc the move probabilities based on visit counts at the root node
        act_visits = [(act, node._n_visits)
                      for act, node in self._root._children.items()]
        acts, visits = zip(*act_visits)
        act_probs = softmax(1.0/temp * np.log(np.array(visits) + 1e-10))
        return acts, act_probs
您的程序：
            p = softmax(1.0 / 1.0 * np.log(np.array(visits) + 1e-10))
            move_probs[list(acts)] = p
            # return the prob with temp=1
           。。。
            return move,move_probs

Song的程序中返回给神经网络训练的props是加τ。
而您的程序中返回给神经网络训练的props是不加 τ 的。

**Comment by initial-h** [comment]
我大概明白你的意思了。其实是这样的，当tau接近0的时候，才是你认为的不加tau，这个时候只有一个动作的概率为1，其他都为0。当tau=1的时候，才是真正的和访问次数相关的概率分布，我直接写成temp=1,就相当于我收集的数据一直考虑了这个参数的。宋大佬之前的代码是在训练的时候把temp=1当成参数传进去的，所以我和他是一致的。
另外我分开写的原因在于，alphazero里面写了前面n=30步把tau设置为1，增大探索，之后设置为0，增加准确度。宋大佬的代码里面，做self-play的时候没有考虑这个，我把这点加上了，所以传参直接传temp=1的话就没法根据下了几步来调整tau了，我就把这个参数单独拿出来拆开了。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/1397a8345cc6fcec5c98864d07df5c9ae76dabb9/mcts_alphaZero.py#L266-L278

**Comment by tangbh** [comment]
明白了，非常感谢
