### ISSUE TITLE
policy_value_net_tensorlayer.py一个小问题

### ISSUE THREAD

**Issue by tangbh** [initial-h/AlphaZero_Gomoku_MPI#13]
self.restore_params = []
        for params in self.network_params:
            # print(params,'**'*100)
            if ('conv2d' in params.name) or ('resnet' in params.name) or ('bn' in params.name) or ('flatten_layer' in params.name):
                self.restore_params.append(params)

在restore_params 时，为什么不添加 dense_layer？

**Comment by initial-h** [comment]
这个地方API是用来transfer learning的，在小棋盘上训练参数再训练大棋盘，全连接的参数维度会变化，不能复用，卷积的可以。

**Comment by tangbh** [comment]
明白了，谢谢
