### ISSUE TITLE
迁移学习很神奇啊，有意思！

### ISSUE THREAD

**Issue by tangbh** [initial-h/AlphaZero_Gomoku_MPI#16]
我用训练好的11X11的模型来训练15X15的棋盘，只用了2天时间就有很好的水平，至少我是下不过它了。
另外，我稍微修改了一下 tensorflow的文件，把 tenserlayer 部分去掉了。

**Comment by initial-h** [comment]
确实会快一些，和图像里面用VGG，GoogleNet做参数初始化有点类似。

**Comment by luopeng69131** [comment]
> 我用训练好的11X11的模型来训练15X15的棋盘，只用了2天时间就有很好的水平，至少我是下不过它了。
> 另外，我稍微修改了一下 tensorflow的文件，把 tenserlayer 部分去掉了。

您好，请问下这两个模型状态层是有所不同的，您是如何修改这一部分实现迁移的呢？

**Comment by tangbh** [comment]
作者的程序就有这个功能的。
