### ISSUE TITLE
作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練

### ISSUE THREAD

**Issue by baimantou** [initial-h/AlphaZero_Gomoku_MPI#18]

**Comment by initial-h** [comment]
有的，这里是一个网络两个输出分支，和alphago zero的版本一致。loss里有value loss和policy loss.
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/b1cc50ab59121ce1d03203c11a0665049abf83c6/policy_value_net_tensorlayer.py#L51-L58

**Comment by baimantou** [comment]
你好，我的意思是value network 训练出的权重文件，没有保存吧，还有关于论文中的loss function是通过两个loss（mse和cross-entropy）的和，来更新参数嘛------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 下午3:16
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



有的，这里是一个网络两个输出分支，和alphazero go的版本一致。loss里有value loss和policy loss.
 https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/b1cc50ab59121ce1d03203c11a0665049abf83c6/policy_value_net_tensorlayer.py#L51-L58
 
&mdash;

**Comment by initial-h** [comment]
是有保存的，不知道你看了哪一行的代码觉得没有保存。
对的，loss是求和的，一共三个，policy，value, l2 penalty.

**Comment by baimantou** [comment]
好的，我再仔细看看代码，还有一个问题请教你，mse和cross-entropy对应的policy loss 和value loss的对应关系是咋样的，论文中好像没有提及------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 下午5:42
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



是有保存的，不知道你看了哪一行的代码觉得没有保存。
 对的，loss是求和的，一共三个，policy，value, l2 penalty.
 
&mdash;

**Comment by initial-h** [comment]
不太明白想问什么。。。
policy loss 用的是cross entropy, 拟合的是走每个动作的概率，value loss用的是mse, 拟合的是当前局面输赢的可能性。

**Comment by baimantou** [comment]
看了论文没有找到policy和value分别用的是什么loss于是请教你一下，我想问一下，你是研究生嘛------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 下午5:57
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



不太明白想问什么。。。
 policy loss 用的是cross entropy, 拟合的是走每个动作的概率，value loss用的是mse, 拟合的是当前局面输赢的可能性。
 
&mdash;

**Comment by initial-h** [comment]
已经毕业了。

**Comment by baimantou** [comment]
之前看你的GitHub里的文档资料是中科院自动化研究所的，以为你正在读研究生，就问了一下------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 晚上6:15
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



已经毕业了。
 
&mdash;

**Comment by baimantou** [comment]
你好，还有一个问题，想问你一下，这个棋类的评价函数，是通过value network实现的嘛------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月21日(星期六) 晚上6:15
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



已经毕业了。
 
&mdash;

**Comment by initial-h** [comment]
不好意思，没明白这里评价函数指的什么

**Comment by baimantou** [comment]
一般情况下，博弈游戏不都有评估函数的嘛? 对当前的局面进行评估，我想知道的是zero有没有评估函数 ------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月22日(星期天) 晚上11:13
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



不好意思，没明白这里评价函数指的什么
 
&mdash;

**Comment by initial-h** [comment]
你说的博弈游戏的评估指的是胜负关系的预测吗？如果是的话，可以认为value network在做这个事情。

**Comment by baimantou** [comment]
好的，谢谢了，麻烦你了------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月22日(星期天) 晚上11:35
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



你说的博弈游戏的评估指的是胜负关系的预测吗？如果是的话，可以认为value network在做这个事情。
 
&mdash;

**Comment by baimantou** [comment]
作者你好，我跑了一下你的代码，直接运行的train_mpi.py输出的是（---train epoch :81,total game :0 ）我不太清楚你定义的两个变量self.game_count = 0 # count total game have played&nbsp;和 self.game_batch_num = 10000000 # total game to train 这两个变量不太清楚它们的含义，所以我对这个输出的结果，不是特别明白，不知道（---train epoch :81,total game :0 ）表示的是什么含义
 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"initial-h"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月22日(星期天) 晚上11:35
收件人:&nbsp;"initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com&gt;;
抄送:&nbsp;"软172纪文"<1965281523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)




你说的博弈游戏的评估指的是胜负关系的预测吗？如果是的话，可以认为value network在做这个事情。

**Comment by initial-h** [comment]
多进程的版本要在终端运行，来开启多个进程，分别做训练，评估，收集棋谱。建议先看看readme的How to Run部分。self.game_count统计目前自博弈了几局，self.game_batch_num是总共要训多少局。你运行的方式不对，所以没有进程在自博弈，而train的那个进程在空转，也就是没训。

**Comment by baimantou** [comment]
我明白了，我看了你的readme  你当时是训练了10万局，对吧------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月24日(星期二) 下午5:28
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



多进程的版本要在终端运行，来开启多个进程，分别做训练，评估，收集棋谱。建议先看看readme的How to Run部分。self.game_count统计目前自博弈了几局，self.game_batch_num是总共要训多少局。你运行的方式不对，所以没有进程在自博弈，而train的那个进程在空转，也就是没训。
 
&mdash;

**Comment by initial-h** [comment]
嗯

**Comment by baimantou** [comment]
还有一个疑问，我跑了多进程的程序，我在想啊，多进程是不是真的要比单进程要快，多进程要频繁的io处理啊------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 下午4:50
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



嗯
 
&mdash;

**Comment by initial-h** [comment]
收集一局棋谱，和同时收集几十几百局，效率的提升是显然的。

**Comment by baimantou** [comment]
我明白了，就是就是可以收集更多棋谱在相同的时间，------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月25日(星期三) 晚上9:42
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



收集一局棋谱，和同时收集几十几百局，效率的提升是显然的。
 
&mdash;

**Comment by baimantou** [comment]
作者你好，你的代码中的self.pure_mcts_playout_num 的作用是什么，我们已经有了mcts_aiphaZero.py文件为什么还要mcts_pure.py文件，这个地方不明白。希望可以讲解一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"initial-h"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 晚上9:42
收件人:&nbsp;"initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com&gt;;
抄送:&nbsp;"软172纪文"<1965281523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)




收集一局棋谱，和同时收集几十几百局，效率的提升是显然的。

**Comment by initial-h** [comment]
这个纯的树搜索只是为了在训练的过程中和模型对弈，看看当前模型训练的如何了。

**Comment by baimantou** [comment]
那个参数等于200又表示什么意思呢------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2019年12月27日(星期五) 下午3:51
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



这个纯的树搜索只是为了在训练的过程中和模型对弈，看看当前模型训练的如何了。
 
&mdash;

**Comment by initial-h** [comment]
树搜索的次数

**Comment by baimantou** [comment]
我看了一下代码，你的意思是让纯树搜索和训练的树搜索博弈，根据winner来计算win_ratio 这部分论文好像没有吧，是自己加的嘛，win_ratio不是可以通过value network来计算吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"initial-h"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月27日(星期五) 晚上6:04
收件人:&nbsp;"initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com&gt;;
抄送:&nbsp;"软172纪文"<1965281523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)




树搜索的次数

**Comment by initial-h** [comment]
这一部分都只是用来监控训练的过程的，没过一段时间就和纯的树搜索打10局，看看胜率，如果全胜，就增加纯树搜索的搜索次数再进行对弈。只是为了看看模型有没有变得更好，原论文没有。这部分是从这个大佬的代码里来的[junxiaosong/AlphaZero_Gomoku](https://github.com/junxiaosong/AlphaZero_Gomoku)

**Comment by baimantou** [comment]
作者你好，你的代码中的win_ratio是如何计算的，这个计算公式没有看明白，希望你可以解释一下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"initial-h"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月28日(星期六) 中午12:40
收件人:&nbsp;"initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com&gt;;
抄送:&nbsp;"软172纪文"<1965281523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)




这一部分都只是用来监控训练的过程的，没过一段时间就和纯的树搜索打10局，看看胜率，如果全胜，就增加纯树搜索的搜索次数再进行对弈。只是为了看看模型有没有变得更好，原论文没有。这部分是从这个大佬的代码里来的junxiaosong/AlphaZero_Gomoku

**Comment by initial-h** [comment]
就是打十局，赢算1，平算0.5，输算0，求十局的平均值

**Comment by baimantou** [comment]
论文不是通过value network来确定胜率嘛------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2020年1月11日(星期六) 晚上10:07
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



就是打十局，赢算1，平算0.5，输算0，求十局的平均值
 
&mdash;

**Comment by initial-h** [comment]
那个是在做树搜索的时候用的。这个胜率是评估的时候用的，用来换模型的。原论文打了400局，我这里算力不行，就粗略测了一下。
Each evaluation consists of 400 games, using an MCTS with 1,600 simulations to select each move, using an infinitesimal temperature τ→ 0 (that is, we deterministically select the move with maximum visit count, to give the strongest possible play). If the new player wins by a margin of > 55% (to avoid selecting on noise alone) then it becomes the best player αθ∗, and is subsequently used for self-play generation, and also becomes the baseline for subsequent comparisons.

**Comment by baimantou** [comment]
我记得你之前说过，和纯的mcts打十局，看看胜率，这个胜率是指和纯mcts对打的胜率嘛，然后论文中有打了400局，做一次评估，我就有一点乱了------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2020年1月11日(星期六) 晚上10:13
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



那个是在做树搜索的时候用的。这个胜率是评估的时候用的，用来换模型的。原论文打了400局，我这里算力不行，就粗略测了一下。
 Each evaluation consists of 400 games, using an MCTS with 1,600 simulations to select each move, using an infinitesimal temperature τ→ 0 (that is, we deterministically select the move with maximum visit count, to give the strongest possible play). If the new player wins by a margin of > 55% (to avoid selecting on noise alone) then it becomes the best player αθ&#x2217;, and is subsequently used for self-play generation, and also becomes the baseline for subsequent comparisons.
 
&mdash;

**Comment by initial-h** [comment]
不好意思我没说明白。
在个代码有两个训练的版本，在单进程里，只有和纯树搜索对打做评估，这个只是用来监控一下训练过程，并没有实质性作用。
在多进程的版本里面，除了和纯树搜索打，还有一个和论文一样的更新模型的操作，如果胜率高于55%，就更新模型。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/b1cc50ab59121ce1d03203c11a0665049abf83c6/train_mpi.py#L434-L441

**Comment by baimantou** [comment]
好的，明白了，你的代码play batch size取一，是不是有点小啊，论文中是400对吧，------------------ 原始邮件 ------------------
发件人: "initial-h"<notifications@github.com>
发送时间: 2020年1月11日(星期六) 晚上10:55
收件人: "initial-h/AlphaZero_Gomoku_MPI"<AlphaZero_Gomoku_MPI@noreply.github.com>;
抄送: "baimantou"<1965281523@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [initial-h/AlphaZero_Gomoku_MPI] 作者你好，看了你的代碼，只有policy network 我很好奇你的value network，有沒有訓練 (#18)



不好意思我没说明白。
 在个代码有两个训练的版本，在单进程里，只有和纯树搜索对打做评估，这个只是用来监控一下训练过程，并没有实质性作用。
 在多进程的版本里面，除了和纯树搜索打，还有一个和论文一样的更新模型的操作，如果胜率高于55%，就更新模型。
 https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/b1cc50ab59121ce1d03203c11a0665049abf83c6/train_mpi.py#L434-L441
 
&mdash;

**Comment by initial-h** [comment]
这个play_batch_size是收集selp-play数据用的，用在self.collect_selfplay_data(self.play_batch_size)，不是评估的400，我的代码里面评估是10局，用在win_ratio = self.policy_evaluate(n_games=10,num=num,self_evaluate=1)。因为收集代码的数据外面有一个大循环，所以这里写1也没关系，出来这个函数后会接着进到这个收集数据的函数里。

**Comment by initial-h** [comment]
用问题再新开issue吧，这个太长了
