### ISSUE TITLE
Tricks Discussion

### ISSUE THREAD

**Issue by SeriaQ** [initial-h/AlphaZero_Gomoku_MPI#19]
首先表达一下感谢，看到git上有这么多有同样兴趣而且认真付诸实践的人其实挺开心的。而且repo主你是我见过回答最积极的一个 :D

这里我有几个关于你使用的tricks想和你请教一下：

1. 我认为总共有三种添加noise的方式来增加对局多样性，a) 在select计算score时；b) 在expand分配prior时；c) 在play选择move时。你采用的是第二种，不知道你是否尝试过其他的呢？因为第二种是唯一一种改变了tree本身数据的方式，这样会不会导致training过程很混乱呢？
事实上，在我的尝试中（我的代码是自己从头写的，只是某些算法过程有参考各个repos，所以可能结果会与你们不太一致），第二种是收敛最慢的，而且是最早遇到local minima卡住的...但从你描述的结果来看，他应该是要上限更高

2. 我看了你的代码，似乎没有看到root parallel的内容？只是在多进程收数据。是我漏看了吗，还请指明

3. 不停的evaluation是否有必要？按照alpha zero general的说法，只维护一个最新的model似乎能达到更快的收敛速度。

事实上，我自己先尝试了4子的训练，一切很顺利，policy loss达到2.1的时候，我就已经输多赢少了。然后我就拓展成5子，结果即使试验很多不同的设置，包括网络结构深度、history buffer length、对局噪声甚至是c_puct和tau这样的超参。但一直连先手赢我都做不到，所以想问一下你是否有踩过类似的坑呢？顺便一提，我在训练过程中经常会遇到鞍点之类的，loss不降，继续训练就会慢慢升高，需要我停止再重新从断点train。最后我的policy loss最终在2.0～2.2晃荡，无论怎么调也降不下去了。

谢谢！

**Comment by initial-h** [comment]
1.a)第一种方式你是说算完Q+U再在上面加个随机吗？b)第二种方式我做出来是有效的，不过我和原论文有区别，我在每个节点都加了一点噪声。我觉得这样改变数据结构问题不大。首先噪声的权重很小，只有0.25。其次因为有树搜索的过程，比如我在这个初始化有随机性的树上面做了400次MCTS，那么即使噪声会扰乱初始值，MCTS也可以慢慢修正。最后从Q+U的含义来看，U的目的就是增加探索，我在这个值上做文章，也就是改变一下探索的策略，原理上来看对树是没有任何影响的。c)第三种我之前试过，刚开始有效，但后面很长时间不提升，因为算力有限没法说是训练不够还是这个方式不work。不过，就和Q+U的含义一样，我理解的原因是树搜索做完，结果本来已经是一个比较精确的决策了，如果这个时候加噪声，会扰乱这个好的决策。而且从这个分布里面采样动作和你最后网络拟合的动作的概率分布还有争议。如果你拟合带噪声的分布，这个结果就不准。如果你拟合不带噪声的分布，这个分布和你选取动作的分布就不是同一个分布。这会不会对训练造成影响我也不敢断定。
2.root parallel只在下棋的时候用了，有点机器学习里ensemble的感觉，这里我没写清楚。
3.这个我觉得都可以，应该都有效。evaluate一下方便看看模型有没有提升，方便调试。

loss这个问题，我觉得你2.0的loss不大。不知道你一共训练了多久，收集了多少数据。而且这个loss跟你buffer大小，网络深度，还有L2正则项都有关系，我记得我小棋盘，小buffer的时候loss比较小，后来训练大棋盘的时候loss比较大，但棋力也会提升。loss升高没遇到过，会不会是你训练的轮数赶不上你数据收集的速度。

**Comment by SeriaQ** [comment]
谢谢回复。

1. 你说的有道理，我思考了一下也觉得a)其实并不是一个好选择，因为当搜索次数足够多的时候，根据大数定律，在Q差不多的情况下那些网络预测出来prior大的节点还是会被更多地访问，所以噪声反而没什么用了。另外其实还有第四种方式，就是在参数本身上加噪声，这个春节期间我可能会试一下，如果有效我再来和你分享

2&3. 明白。

4. 我目前是单进程，每完成一局self play，我就会把数据加到data_cache里，然后重新随机选取部分数据通过5次iter来训练模型，再用更新后的模型进行下一次self play。总共训练了1700局（使用c型加噪方式），policy loss 达到2.1左右，就再也不降了。你的回答似乎说明你的强棋力模型loss也差不多咯？那的确很奇怪，我要再研究一下

**Comment by initial-h** [comment]
1700局太少了，我的10万局都挺少的其实。

**Comment by SeriaQ** [comment]
1700虽然少，但问题是我的loss也到了不错的程度了。而且即使我再训练，loss也只会持平甚至上升，这算是我最困扰的地方了 :(

**Comment by initial-h** [comment]
loss没问题，问题是你拟合的棋谱不是高质量的棋谱，因为刚开始的网络很不准，下棋也是臭棋，拟合这个数据再好也不会下出很好的棋。

**Comment by SeriaQ** [comment]
是的，我会想个办法进行一下质量把控。
谢谢回答

**Comment by SeriaQ** [comment]
春节的时候我也改成了多进程self play，并且放慢了train网络的频率，果然棋力就上来了，loss也下降到1.8左右了。
但现在发现两个新的现象，想请教一下：
1. 在人机实战时，AI经常会在下到40手左右的时候，突然不去堵活三，而是自顾自地进攻导致输棋。我回想了一下，在早期这种现象发生的时间点要更早，所以不知道是不是只要接着训练下去就会变好，请问你有碰到过这种情况吗？
2. 其实还是关于第一个问题的延伸思考，就是我发现在训练过程中，还是有很多自对弈是在十几步就结束了，说明是某一方犯了很愚蠢的错误而非碰到双活三不得已输的。原因我觉得要么是因为我在决策时加了噪声，要么是因为我的temperature一直设的是1，它采样到了致命的下法。但是我发现即使把噪声降得很小以及temperature调小也还是经常出现这个情况，以及事实上我觉得这样做不太好，因为自对弈的随机性和扩展性就没有了。所以想请教一下你的经验

谢谢。

**Comment by initial-h** [comment]
放慢了train网络的频率？这个我感觉一直训着就好了。除非是断掉了样本丢失了，想要接着保存的模型训。一般这种先把buffer填满一点再训，避免样本太少网络被过拟合了。
1. 如果训练不够多的话是可能有这个问题的，一个原因是五子棋相比围棋来说，五子棋通常比较短，很容易突然结束，训练不够的话可能没有见过40手的棋谱，所以我在训练的时候就print了棋谱的长度来调整探索。我发现通常十几二十手就可以结束。如果接着训，应该会变好。
2. 接着第一个问题，如果要训练好的话，是需要各种长度的棋谱的，就是下棋比较蠢也没关系，因为刚开始蠢一点可以增加棋谱的多样性，就算是网络训练好了也需要它走一些臭棋以此来得到不同的样本。所以paper里有个first move 的参数来调整temperature。前30步为1，增加多样性，后面的接近0，增加准确性。这个操作在我的训练过程中感觉比较关键，我设置的是前12步。

**Comment by SeriaQ** [comment]
基本都同意，就是最后一句在12步之后temperature设为0，这个感觉有矛盾。因为这样的话长度大于12步的棋谱步就很难有臭棋来增加多样性了吗？

**Comment by initial-h** [comment]
刚开始需要有不同的开局方式，之后就需要在此基础上找到最优决策，可以理解成从残局开始认真下。这样可以保证样本多样性和样本质量。不过这都是经验性的东西。
