### ISSUE TITLE
有关该项目和原版的差异的一些疑问

### ISSUE THREAD

**Issue by tml104** [initial-h/AlphaZero_Gomoku_MPI#2]
1、这个是原版下AlphaZero_Gomoku的一个issue：
https://github.com/junxiaosong/AlphaZero_Gomoku/issues/54
除了这个issue外，也有很多人指出即使已经训练了很多盘棋，原版模型在棋盘边缘上的判断上依然有明显失误（比如不会主动去堵对手在边界上形成的活三，或者在边界上有必杀棋但不走）。
并且个人测试了一下，用一个已经训练了1500局的模型在9*9棋盘下五子棋时，增大playout（个人测试是到5000以上）能稍微缓解这种现象的发生，但依然不能保证在主战场还在棋盘中央的时候，AI会堵棋盘边缘的活三。而playout增加到5000的时候下一步棋已经需要快半分钟的时间了，因此继续增大playout可能没法解决这个问题。
这个issue则指出这个现象的发生可能是因为神经网络是CNN的zero padding导致的，如果增加边缘特征平面可以解决这种问题：
https://github.com/junxiaosong/AlphaZero_Gomoku/issues/68

我注意到您的模型似乎没有这个问题，但不是很清楚是不是因为使用了残差网络，所以想请教一下您是否有在原来的基础上添加特征平面？还是仅仅将CNN换成了残差网络进行训练？

2、
我注意到您的模型在相同的局面下可能会下在不同的地方，而原版模型在相同模型下只会下在同一个地方，所以想问一下您的策略pi最终是如何确定的。

3、
似乎我没有安装mpi4py也能正常跑human_play.py下棋，所以mpi4y是只有在train时才一定要装吗？

最后感谢拨冗回答。

**Comment by initial-h** [comment]
这几个问题我也遇到过，为了让后来的人少踩坑，我在**README的Some Tips部分**写了一些我踩过的坑和解决办法。

1、这个问题我个人理解是比如CNN卷积核是3x3，stride是1x1，那么矩阵最外圈只会被提取一次，中间部分可以被提取三次，所以会出现这个问题。我通过**在卷积之前补两圈零**解决了这个问题。不过这个**都是玄学**，具体可能有更深层次的原因。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L243
2、之所以下棋会走不同的地方，是因为我在网络预测部分给输入特征**加入了随机的旋转和镜像反转**，这样可以使得每次网络的输出有细微差异，从而下出不一样但又合理的走法。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L166-L203
3、MPI只在需要并行的时候会用上。human_play.py和train.py是单进程的测试和训练，不需要MPI库。而human_play_mpi.py和train_mpi.py是多进程并行的代码，这两个需要MPI。
对于自己下棋来说，human_play.py就足够了，但是要想训练大棋盘的话，考虑到巨大计算量，并行的方式会快很多。

**Comment by tml104** [comment]
> 这几个问题我也遇到过，为了让后来的人少踩坑，我在**README的Some Tips部分**写了一些我踩过的坑和解决办法。
> 
> 1、这个问题我个人理解是比如CNN卷积核是3x3，stride是1x1，那么矩阵最外圈只会被提取一次，中间部分可以被提取三次，所以会出现这个问题。我通过**在卷积之前补两圈零**解决了这个问题。不过这个**都是玄学**，具体可能有更深层次的原因。
> [AlphaZero_Gomoku_MPI/policy_value_net_tensorlayer.py](https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L243)
> 
> Line 243 in [ab69b18](/initial-h/AlphaZero_Gomoku_MPI/commit/ab69b180dc37ee7ccd5d266f893625f12bb0373f)
> 
>  inputlayer = tl.layers.ZeroPad2d(inputlayer,2,name='zeropad2d') 
> 
> 2、之所以下棋会走不同的地方，是因为我在网络预测部分给输入特征**加入了随机的旋转和镜像反转**，这样可以使得每次网络的输出有细微差异，从而下出不一样但又合理的走法。
> [AlphaZero_Gomoku_MPI/policy_value_net_tensorlayer.py](https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L166-L203)
> 
> Lines 166 to 203 in [ab69b18](/initial-h/AlphaZero_Gomoku_MPI/commit/ab69b180dc37ee7ccd5d266f893625f12bb0373f)
> 
>      def policy_value_fn_random(self,board,actin_fc,evaluation_fc): 
>          ''' 
>          input: board,actin_fc,evaluation_fc 
>          output: a list of (action, probability) tuples for each available 
>          action and the score of the board state 
>          ''' 
>          # like paper said, 
>          # The leaf node sL is added to a queue for neural network 
>          # evaluation, (di(p), v) = fθ(di(sL)), 
>          # where di is a dihedral reflection or rotation 
>          # selected uniformly at random from i in [1..8] 
>   
>          legal_positions = board.availables 
>          current_state = np.ascontiguousarray(board.current_state().reshape( 
>              -1, self.planes_num, self.board_width, self.board_height)) 
>   
>          # print('current state shape',current_state.shape) 
>   
>          #add dihedral reflection or rotation 
>          rotate_angle = np.random.randint(1, 5) 
>          flip = np.random.randint(0, 2) 
>          equi_state = np.array([np.rot90(s, rotate_angle) for s in current_state[0]]) 
>          if flip: 
>              equi_state = np.array([np.fliplr(s) for s in equi_state]) 
>          # print(equi_state.shape) 
>   
>          # put equi_state to network 
>          act_probs, value = self.policy_value(np.array([equi_state]),actin_fc,evaluation_fc) 
>   
>          # get dihedral reflection or rotation back 
>          equi_mcts_prob = np.flipud(act_probs[0].reshape(self.board_height, self.board_width)) 
>          if flip: 
>              equi_mcts_prob = np.fliplr(equi_mcts_prob) 
>          equi_mcts_prob = np.rot90(equi_mcts_prob, 4 - rotate_angle) 
>          act_probs = np.flipud(equi_mcts_prob).flatten() 
>   
>          act_probs = zip(legal_positions, act_probs[legal_positions]) 
>          return act_probs, value 
> 
> 3、MPI只在需要并行的时候会用上。human_play.py和train.py是单进程的测试和训练，不需要MPI库。而human_play_mpi.py和train_mpi.py是多进程并行的代码，这两个需要MPI。
> 对于自己下棋来说，human_play.py就足够了，但是要想训练大棋盘的话，考虑到巨大计算量，并行的方式会快很多。

抱歉，才发现原来您的Readme里都有写……是我读得不够仔细。
再次感谢耐心解答
