### ISSUE TITLE
关于train.py的一些疑问

### ISSUE THREAD

**Issue by LLYYKK** [initial-h/AlphaZero_Gomoku_MPI#21]
作者您好，想请问一下有关单线程train.py的问题。
我发现，在data_buffer未满之前，tmp_buffer随着训练局数的增加而增大，而step的长度又与tmp_buffer相关。也就是说在在data_buffer未满之前，policy_update()里的step是不断增大的，耗时也是不断地在增加的。而每次训练结束后，tmp_buffer里的数据并未保存。

那这是否意味着，一次训练1000局与分十次每次在上一次的权重上训练100局的时间是不同的？
这二者同样一共训练了1000局，哪个效果更好呢？

**Comment by initial-h** [comment]
我数据是存在data_buffer里的，tmp_buffer的作用是把数据顺序打乱，所以每次训练都重新打乱。训练的方式和监督学习一样，每次抽一个batch，把所有数据train一遍，算是一个epoch。

这个训练的过程是循序渐进的，有了data都会存在buffer里不断进行训练，除非buffer满了被挤出去，所以这个差异不好用你说的这个方式衡量。

**Comment by LLYYKK** [comment]
> 我数据是存在data_buffer里的，tmp_buffer的作用是把数据顺序打乱，所以每次训练都重新打乱。训练的方式和监督学习一样，每次抽一个batch，把所有数据train一遍，算是一个epoch。
> 
> 这个训练的过程是循序渐进的，有了data都会存在buffer里不断进行训练，除非buffer满了被挤出去，所以这个差异不好用你说的这个方式衡量。

谢谢作者回答！其实我想表达的意思是，我每次运行train.py，buffer都会从0开始不断变大。那是不是每一轮的step数也在增大，耗时也在增加，直到buffer满了之后每轮的耗时才固定下来？
每一轮epoch都比前一轮的时间长h一些，是否会导致越训练耗时越长呢？

假如我把buffer_size设置为一个较小的值（比如说batch_size的10倍），这样子长时间训练肯定会快很多，但是不是训练效果会打折扣呢？比起大的batch_size而言

**Comment by initial-h** [comment]
对的，训练时间会变长，不过数据变多要想拟合好，train更多step也是合理的。你可以看看loss的下降趋势，如果精度足够也可以适当少训练。

buffer_size较小的话，棋谱的数量太少，多样性不够。肯定是棋谱越多，训练越久，效果越好。所以我在多进程的代码里面专门拿了一个进程不间断训练模型。如果算力不够，你可以在step，buffer size等等上面进行调整，适当trade off，不过效果肯定会有一定损失，而且怎么在有限算力上最大化效果就要根据训练效果自己尝试了。如果算力够的话就不用考虑这些，直接加算力就好了。

**Comment by LLYYKK** [comment]
> 对的，训练时间会变长，不过数据变多要想拟合好，train更多step也是合理的。你可以看看loss的下降趋势，如果精度足够也可以适当少训练。
> 
> buffer_size较小的话，棋谱的数量太少，多样性不够。肯定是棋谱越多，训练越久，效果越好。所以我在多进程的代码里面专门拿了一个进程不间断训练模型。如果算力不够，你可以在step，buffer size等等上面进行调整，适当trade off，不过效果肯定会有一定损失，而且怎么在有限算力上最大化效果就要根据训练效果自己尝试了。如果算力够的话就不用考虑这些，直接加算力就好了。

谢谢作者的细心回答！！！
