### ISSUE TITLE
关于MPI版本的一些疑问？

### ISSUE THREAD

**Issue by LLYYKK** [initial-h/AlphaZero_Gomoku_MPI#22]
作者您好，我在比较MPI版本和单线程版本中，发现了一个显著的区别。

在单线程版本中，训练时一方是current_mcts_player，另一方是test_player。
在多线程版本中，除了上述两个之间的对弈，还多了current_mcts_player与mcts_player_oppo的对弈，后者看起来更加像是一种"不断超越自我的修炼"。

这差异似乎还直接导致运行MPI版时CPU发热量不正常。3线程情况下，CPU占用率80％但发热却很厉害...

所以想请教一下，单线程版本和多线程版本中的这种差异是出于何种考虑呢？

**Comment by initial-h** [comment]
这个地方和paper保持一致，参考issue https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/18#issuecomment-573323755

发热是正常的，几个进程同时运行，占用率过高。普通电脑训练比较费劲，服务器会好一点。

**Comment by LLYYKK** [comment]
> 这个地方和paper保持一致，参考issue [#18 (comment)](https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/18#issuecomment-573323755)
> 
> 发热是正常的，几个进程同时运行，占用率过高。普通电脑训练比较费劲，服务器会好一点。

好哒，谢谢回答！
