### ISSUE TITLE
关于MCTS_Pure的一些疑问？

### ISSUE THREAD

**Issue by LLYYKK** [initial-h/AlphaZero_Gomoku_MPI#23]
作者您好，想请教一下MTCS_Pure的意义？
据我这些天对代码的研究，在单线程版本中，它在生成棋谱的过程中充当对手。而在多线程版本中，它则仅仅是在评估时作为对手。

所以想请教一下它的具体作用是什么呢？为何在单线程版本中选择它作为对手，而在多线程版本中则只用作评估？pure_mcts_playout_num的大小是否会影响它的水平，是否越大越好呢？

盼望您的回复。

**Comment by initial-h** [comment]
这个地方可能有误解，不管在哪个版本，收集数据都是通过自对弈产生的，MTCS_Pure没有参与。https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train.py#L98
MTCS_Pure的作用只是和模型对打一下，评估一下当前效果，方便调试。如果你在训练过程中不知道棋力有没有进步，是不知道代码有没有bug，参数设置是否work的，这个就是print出来让你知道模型确实在慢慢变强。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train.py#L166
多进程版本多出来的部分是和之前保存的最优模型对打，用来更换最优模型继续收集数据。https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/18#issuecomment-573323755

**Comment by LLYYKK** [comment]
> 这个地方可能有误解，不管在哪个版本，收集数据都是通过自对弈产生的，MTCS_Pure没有参与。
> 
> https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train.py#L98
> 
> 
> MTCS_Pure的作用只是和模型对打一下，评估一下当前效果，方便调试。如果你在训练过程中不知道棋力有没有进步，是不知道代码有没有bug，参数设置是否work的，这个就是print出来让你知道模型确实在慢慢变强。
> https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train.py#L166
> 
> 
> 多进程版本多出来的部分是和之前保存的最优模型对打，用来更换最优模型继续收集数据。[#18 (comment)](https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/18#issuecomment-573323755)

感谢您认真的解答！我之前可能是把收集函数和评估函数里的代码看混了，仔细看一下的确如您所说。
不过既然收集自对弈数据与pure-mcts无关，而且在15×15的大棋盘上，无论是单线程还是多线程中，与pure-mcts对打这部分代码占用了不少计算资源，但其实并没有太大的影响。那是不是意味着可以减少甚至不进行评估呢？

举例个子，单线程版本中默认每100局测试一次。在15×15中，一开始的测试几乎都是全输的，于是我索性让它先别测试了，节省时间。如果测试则我自己另外执行部分代码来测试。

而多线程版本中，一直有个rank在进行测试，个人感觉它似乎也是占用了不少资源，而且不停地print的信息，使得看起来有点混乱哈哈。

因此我觉得也许在大棋盘上，用pure_mcts评估模型的频次可以适当减少，不必经常评估，以此达到节省时间的目的。（PS:其实本质上是我电脑性能太弱了哈哈）

**Comment by initial-h** [comment]
对的，确定算法都调好的话，这部分可以直接去掉。
