### ISSUE TITLE
关于Dihedral Reflection or Rotation和node概率p的一些困惑

### ISSUE THREAD

**Issue by luopeng69131** [initial-h/AlphaZero_Gomoku_MPI#24]
作者，您好！看了你的并行实现代码深感佩服，但仍有一些困惑，想要请教。一方面是关于Dihedral Reflection or Rotation这部分实现我看了很多遍还是不大理解，这个是随机旋转节点概率赋值吗？从论文到代码一直不是很能理解这部分，一开始以为单纯对应训练数据增强，后来看了你的代码后感觉是单独一部分，但始终不大理解；第二个是关于Tree node的概率p赋值，这个概率我看了下并未根据可行动作重新进行归一化（某个节点分支的可行节点的概率和不为1），这个不影响吗，亦或者是我看的不大仔细，还麻烦您稍作指点！

**Comment by initial-h** [comment]
paper里面，这个是把状态和概率做相同的旋转操作，喂给网络去拟合，相当于做数据增强。对应代码https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train_mpi.py#L92-L104
除了这个之外，我在和人下棋的时候也做了旋转操作，再喂给网络，再旋转回来给出动作，是为了下棋多元一点，不会每次输出同一个动作。参考https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/2#issuecomment-453711831

tree node的概率和是1的，你指的是哪一行代码？

**Comment by luopeng69131** [comment]
作者您好，感谢您的回复。关于第一个问题中，无论是数据增强还是下棋时候的随机策略，对于输出的动作中首先进行一个flipud操作，中间夹着转回来的操作，最后在flipud回来。我的理解是这个flipud操作的顺序使得本来与状态正确对应的动作却产生不可确定的旋转，相当于噪声或者随机，可以这么理解吗（因为若是去除这两个flipud，以下棋部分为例，则会正好会转回去，不会有任何变化）？
`equi_mcts_prob = np.flipud(act_probs[0].reshape(self.board_height, self.board_width))
        if flip:
            equi_mcts_prob = np.fliplr(equi_mcts_prob)
        equi_mcts_prob = np.rot90(equi_mcts_prob, 4 - rotate_angle)
        act_probs = np.flipud(equi_mcts_prob).flatten()`
关于第二问题中的概率部分
`act_probs = zip(legal_positions, act_probs[legal_positions])`
以这句代码为例，是policy_value_fn_random函数里的，这个act_probs是用来扩展节点的，这个act_probs如果不取出legal_positions部分，应该是和为1的（经过了softmax），但是取出后赋值给树节点，因为取出的只是act_probs的一部分，因此得到的扩展出来的树节点的p之和应该是不为1，这个不知道我理解对了吗，还是看漏了，亦或者这样本身影响不是很大。

**Comment by initial-h** [comment]
这里prob有个flipud的操作后才能刚好和state位置对上。就像我后面注释写的那样，因为网络最后输出全连接层是一个向量，变成棋盘的矩阵后其实是从上往下排列的，而我们的棋盘和index的关系是从下往上的，所以需要换一下顺序。也就是
[0,1,2,3,4,5,6,7,8] 
->
  [0,1,2]       
  [3,4,5] 
  [6,7,8] 
-> 
[6 7 8]
[3 4 5]
[0 1 2]

随机初始化的网络会有你说的这个问题，不过随着训练这个问题会慢慢避免，因为data从mcts里出来之后，非法位置的概率都会是0。

**Comment by luopeng69131** [comment]
明白了，这段注释我看到了，但当时只理解为你在解释flipud，并没完全与位置联系再一起。但听完你解释后，仔细想想，发现这个下棋的随机策略真是妙哉，不仅是引入了随机，而且也充分利用到数据增强给网络拟合带来的效果，确实是很有趣。谢谢您的耐心回复，让我受益匪浅。
