### ISSUE TITLE
关于MPI版本中棋力没有进步的问题？

### ISSUE THREAD

**Issue by LLYYKK** [initial-h/AlphaZero_Gomoku_MPI#25]
作者您好。最近我在多线程版本中训练了上千局后，发现当loss下降到3.1左右时就不再下降了，自对弈长时间保持5:5的战绩。但是实测水平却还是比较菜。

我的参数和源代码保持一致，训练了不到2000局。现在也不知道这个模型是不是出了差错，目前把参数从400调整为了1600再进行训练，若无改善可能要重新训练了。

不知道作者有没有碰到过类似的情况呢？
盼望您的回复。

**Comment by initial-h** [comment]
训练局数还是太少了，估计上万把才能看出来有点趋势。自对弈5:5没有关系，说明模型还没有明显变强，还在用当前模型收集数据，这是正常的。

n_playout = 400应该可以训出来的，调大肯定也行。另外，刚开始想看看棋力有没有提升，和MCTS_Pure的对打可以看得比较明显，这也是之前我保留这部分的原因。

**Comment by LLYYKK** [comment]
> 训练局数还是太少了，估计上万把才能看出来有点趋势。自对弈5:5没有关系，说明模型还没有明显变强，还在用当前模型收集数据，这是正常的。
> 
> n_playout = 400应该可以训出来的，调大肯定也行。另外，刚开始想看看棋力有没有提升，和MCTS_Pure的对打可以看得比较明显，这也是之前我保留这部分的原因。

谢谢作者的回答！
