### ISSUE TITLE
关于模型的一些疑惑

### ISSUE THREAD

**Issue by sliver2000** [initial-h/AlphaZero_Gomoku_MPI#26]
作者您好，我是刚入门不久的新手，因为对tensorflow不甚了解，所以想把网络改写成pytorch的。但是在研究代码和改写的过程中对多线程版本中保存的模型有一些疑惑，想向您请教一下，谢谢！
1、`if len(self.data_buffer)>self.batch_size*5:
                        # training

                        # print('`'*50+'data buffer length:{}'.format(len(self.data_buffer)))
                        # print()
                        print_out = True
                        if print_out:
                            # print some training information
                            print('now time : {}'.format((time.time()-start_time)/3600))
                            print('training ...',)
                            print()
                        loss,entropy = self.policy_update(print_out=print_out)

                        # save model to tmp dir, wait for evaluating
                        self.policy_value_net.save_model('tmp/best_policy.model')`
在单线程版本中，模型每50盘棋保存一次，而在多线程版本中，模型每一盘棋都要保存一次模型，这样的理解对吗

2、关于save_numpy和load_numpy，为什么在多线程版本中要保存一个这样的东西，它的作用是什么，一直不明白，如果在policy_evaluate的时候不读取这些参数，会出现什么情况

3、`if os.path.exists('tmp/best_policy.model.index'):`
请问这个.model.index文件是起到什么作用，和.model的模型文件有什么联系

**Comment by initial-h** [comment]
1. 这里是rank==0的部分吧，这是每轮训练完都保存一个临时的模型，和下棋没有关系
2. 这个是用来保存和加载一个当前最优模型作为对手，然后用新训练的模型和它对打看胜率是否过0.55。tf save的是最新的自己，numpy save的是最新的对手。其实也可以用tf的方式保存，后面没再改了
3. 这只是tf保存模型生成的文件，它在读.model的时候内部会调用，这里我只是用一个文件来判断当前是不是有模型了。.data保存参数，.index你可以看出做一些索引和参数，checkpoint是读模型的入口。

**Comment by sliver2000** [comment]
感谢作者的解答！

另外想问一个问题，就是我在多线程第一次训练的时候后台只有两个进程使用了显卡的显存（约11%），但是我中断训练再重新恢复的时候，在（if rank not in {0, 1, 2}）恢复模型的过程中显卡直接就爆了，这时候发现后台几乎每一个进程都占用了约11%的显卡显存。GPU的显存是8G，请问这样的问题产生的可能原因是什么

**Comment by sliver2000** [comment]
中断训练前正好生成了第一个'model/best_policy.model'，后来恢复训练进入‘if os.path.exists('model/best_policy.pth'):’这个循环，显存就爆了

**Comment by initial-h** [comment]
按道理原本就应该是每个进程占用一部分显存，你一共开了多少个进程，是在命令行运行的mpiexec吗？

**Comment by sliver2000** [comment]
抱歉...找了好几天才发现，应该是我改的代码有问题#-_-，同样的网络结构，一个进程占的显存是没改之前的四五倍，只能开10个以内的进程了，谢谢作者
