### ISSUE TITLE
有没有pytorch版本的呢？

### ISSUE THREAD

**Issue by apocalypse-revelation** [initial-h/AlphaZero_Gomoku_MPI#27]
如果要转为pytorch版的，修改policy_value_net的模块就可以了吧？

**Comment by initial-h** [comment]
对的，不过模型怎么从tf转到pytorch要搜一下怎么做。

**Comment by apocalypse-revelation** [comment]
@initial-h 谢谢，另外我想问一下 train.py里的 batch_size、buffer_size、data_buffer以及play_batch_size分别代表什么意思呢？

**Comment by initial-h** [comment]
data_buffer是存数据的队列，buffer_size是这个队列的大小。batch_size是训网络的batch大小，play_batch_size是每下多少局训练一次网络。

**Comment by apocalypse-revelation** [comment]
@initial-h 非常感谢！
