### ISSUE TITLE
16G的内存，data_buffer设置多少合适呢？

### ISSUE THREAD

**Issue by apocalypse-revelation** [initial-h/AlphaZero_Gomoku_MPI#28]
另外train.py中的game_batch_num是什么意思呢？

**Comment by initial-h** [comment]
如果你网络放GPU上，估计50W也能放得下，10W20W也行。不过你台式机单进程训练的话，时间会很长，很难训练一个大棋盘。
game_batch_num是收集数据的轮数，每轮收集play_batch_size局训练一次，game_batch_num*play_batch_size=总的训练局数。

**Comment by apocalypse-revelation** [comment]
@initial-h 谢谢你耐心的回答！再问一下 net.py里的policy_value和policy_value_fn有什么区别呢？

**Comment by initial-h** [comment]
policy_value_fn和policy_value_fn_random是policy和value的输出函数，其中policy_value_fn_random带有状态的旋转和翻折，具有一定的随机性，policy_value_fn没有随机性。
policy_value是这两个函数的中间函数，用session来调用网络的。

**Comment by apocalypse-revelation** [comment]
@initial-h 谢谢！还有就是：
1.如果只训9x9的大小，block设定几个比较合适？
2.我个人电脑的配置是3600+2060super，单进程一周内能跑出比较好的模型吗？

**Comment by initial-h** [comment]
1.4个够了
2.9x9可以。其他参数也可以适当调小节约内存和显存，比如
```
self.batch_size = 256
self.buffer_size = 100000
self.first_n_moves = 6 (mcts_alphaZero.py里)
self.feature_planes = 4 (game_board.py里)
```
如果能开多进程，比如6个，把评估的进程注释掉5个收数据1个训练会更快。

**Comment by apocalypse-revelation** [comment]
@initial-h 
1.谢谢，我改成resnet确实好一点，不过时间大量花费在self-play上，使用gpu的利用率也不到20%。是单进程的原因吗？
2.另外，我是基于@junxiaosong大神的代码写的，如果要换成并行，是不是只要改它的train.py就可以了？
3.最后一个疑问就是：human_play_mpi和train_mpi.py这两个有什么区别呢？（如果要实现mpi训练收集数据并训练网络，而后人机对战是否需要用到human_play_mpi？）

下图是我单进程+3 blocks训练 8_8_5的gpu情况，利用率太低且也没占满。
![1](https://user-images.githubusercontent.com/38872936/77602851-81406c00-6f49-11ea-8e13-e301ad62fe2a.png)

**Comment by apocalypse-revelation** [comment]
4.使用3个block训练6_6_4的棋局,自我对弈一局就要花费1分钟;而自我对弈8_8_5一局要3分钟，这个在单线程里能算正常吗？（start_self_play这个方法的用时非常长，而且使用cpu比gpu快5-6倍？？？）但是确实loss是在不断下降了（6_6_4对弈20局左右就从4.6降到了3.8)。
5.不知道你所说的局数是否算棋盘翻转后扩充了8倍数据的局数还是算运行start_self_play()这个方法的次数

**Comment by initial-h** [comment]
1.这是正常的，self-play是在cpu上做的，只有训练的时候GPU利用率会上去。可以看看cpu利用率如何，没满的话可以尝试多进程。
2.可以的，我也是在宋大佬上面接着做的。
3.train_mpi.py用来训练的，human_play_mpi训练好模型下棋用的，可以看看我的readme。测试可以直接跑单进程的human_play.py效果就不错了。
4.GPU应该还是会比cpu快的，你可以把棋谱长度print出来看看，对比对比速度。
5.局数是最原始的局数，不算数据增强。

**Comment by apocalypse-revelation** [comment]
@initial-h 
对于(4.)这点，我在get_move_probs（就是你的get_move_visit)加了观察时间的，发现平均move一步在cpu上大概1.5s左右（cpu利用率50+）。然后网络改为用gpu后(c和g的利用率都低于20)，get_move_probs耗时平均5-7s左右。（这个还是基于最初@junxiaosong的那个浅层的网络。如果用resnet：3个block，256size在gpu上用时10s）人都晕了，训练太久了。。。

**Comment by initial-h** [comment]
几秒钟走一步是有可能的，不过比cpu慢不清楚了。我之前的配置感受是网络越深，gpu的速度越明显，网络浅的话差异不大，我是19个block。
你可以试试跑一下human_paly.py看看模型下一步多长时间。我之前在pc机上测试，400次树搜索，确实有明显感觉等待，但是也没有很夸张。

**Comment by apocalypse-revelation** [comment]
非常感谢！！我再研究研究。
