### ISSUE TITLE
问一个比较低级的关于单GPU训练的问题

### ISSUE THREAD

**Issue by bingshen** [initial-h/AlphaZero_Gomoku_MPI#3]
你好，我想问一下为什么rank=0,1,2的这3个进程在你的代码当中cuda都是默认为True，但是当只有一个GPU的时候，有方案可以让多个进程同时占用一个GPU资源么？我在代码中没有看到有指定各个进程占用的GPU资源量，tensorflow会自动分配给各个graph显存和运算资源么？

**Comment by initial-h** [comment]
如果GPU显存没占满的话，会自动继续往上放的，也就是多个进程同时占用一个GPU。
但是速度能提升多少还和GPU的计算能力有关。
比如一个网络加上batch大小的数据占了3G显存，一个GPU12G，那只要显存没满，三个甚至四个进程的网络都可以放在这张卡上。
但是计算速度快了多少要看算力是不是跑满了。比如一个程序大约占50%算力，那两个进程就会占满这张卡，放第三个进程的时候虽然显存够能放上去，但是计算速度不会再提高了。

**Comment by bingshen** [comment]
哦哦，原来如此，谢谢了！
