### ISSUE TITLE
关于白棋的退火温度的疑问

### ISSUE THREAD

**Issue by sliver2000** [initial-h/AlphaZero_Gomoku_MPI#30]
在没有禁手和交换的五子棋下，黑棋有很大的优势，而围棋就算是前40步偶尔下一两步坏棋，也可以翻盘，至少下两三百步是没有问题的。五子棋白棋如果还倾向于探索的话，会不会导致过快的陷入劣势而使得棋局很快结束，让自对弈棋谱的价值变低
也就是在前12步让黑棋探索新下法，而让白棋保持最强应对，部分抵消黑棋先手的优势，会不会对自对弈棋谱质量有所改善呢，期待作者的解答，谢谢！

**Comment by initial-h** [comment]
很不错的想法，可以试试看。
