### ISSUE TITLE
关于五子棋执黑第一步和禁手问题？

### ISSUE THREAD

**Issue by LLYYKK** [initial-h/AlphaZero_Gomoku_MPI#31]
作者您好，最近我想在您的代码上进行一些拓展，比如设置黑先第一步棋必须下正中，同时加入一部分禁手规则的限制，实现AI在有禁手规则限制下进行自我对弈。

从其他的issues了解到貌似可以增大噪音来增加第一步走正中的概率，但这显然还是有不确定性的，那否可以通过代码实现第一步必须走中呢（只考虑15X15的棋盘）？

关于禁手规则，考虑到五子棋本身就是一个先手必胜的游戏，应当加入禁手规则。那是否可以直接在原来五个成一线的胜负判定基础上，额外加入规则限制呢？比如说当黑方下出某种禁手，便直接判负。

期待您的回复。

**Comment by initial-h** [comment]
这个直接修改`game_board.py`就行，设置初始棋盘有黑子在正中，然后加上禁手规则。

**Comment by LLYYKK** [comment]
谢谢作者回答，我试着在has_winner那里加入了"当第一步棋的位置不在112上（即不在15×15棋盘的中元上），判黑棋负"的规则。效果似乎还不错，不需要太久AI便能意识到第一步必须下在正中。
