### ISSUE TITLE
大神您好，有问题想请教一下

### ISSUE THREAD

**Issue by 161220028jcdai** [initial-h/AlphaZero_Gomoku_MPI#33]
您好，我想请教一下在mtcs_alphazero.py中的expand中，那个dirichlet noise的参数数值的含义和具体作用是什么，加到不同的地方会怎么样。
比如您在11x11的棋盘设置的是0.3，是根据什么来决定这个值的。您在注释中写到20x20的应该要用0.03，这个值是通过数学方法计算出来的吗，还是在一个大概的范围内调试出来的。
我目前大一对这个强化学习很有兴趣，不过知识有限可能问的问题比较低级，不过这个参数的含义我的确有点搞不明白，其他地方基本都能看懂。麻烦大神解答一下，谢谢了

**Comment by initial-h** [comment]
加噪声的目的是为了给不同的动作加上随机性。而dirichlet noise的好处是可以调节噪声之间的差异，也就是这个地方的0.3，可以使得加上的噪声更有区分度。如果加上的噪声大多都在某一个值左右，其实加和不加就没有差异性了。
关于参数的选择，dirichlet 分布是Beta分布的高维形式，是一个高维分布，所以控制这种差异性是和随机变量的维度有关，体现在这里也即是棋盘的大小了。这里参数选择的标准是，既使得加入的噪声之间有差异性，不要全都差不多大小，同时又避免噪声过于极端，也就是某个噪声是1，其他全是0这种情况。
这个参数也是自己人为确定的，不一定是最好的。你可以试试这个函数，具体感受一下。

**Comment by 161220028jcdai** [comment]
好的谢谢您，看了您说的以后我查了一下有关知识然后结合您解释的思考了一下，想请您看一下我这样理解对不对：如果不加噪声的话，那在“探索-利用”的平衡中相当于只利用蒙特卡洛树搜索返回的概率而不会去探索其他地方的落子了，就会减少样本的多样性。加了这个噪声的话可能会随机地让一些蒙特卡洛树搜索返回概率不高的点变高从而让AI尝试去走这些点，就有可能发现一些新的招法。然后如果这个噪声的参数过小的话，相当于没加，并不会去探索新的点；如果过大的话，又会产生过多的招法就跟乱下差不多了。可以这样理解吗

**Comment by initial-h** [comment]
基本是这样。需要注意的是代码里面有一个0.75和0.25的权重，也就是有0.25权重的概率是随机性赋予的，不管参数是0.3还是0.03，这个比例是不会变的。这里的关键是这些概率赋予给谁，以及如何赋予，dirichlet在这里就是干这个事情的。相当于没加的意思是，每个动作可能都加了0.01，那么他们的相对大小还是没有发生变化，那么探索的搜索优先级就不会改变，所以相当于没加。过大其实是这0.25的概率过于集中到某一个动作上，这也是不利于探索的。

**Comment by 161220028jcdai** [comment]
哦好的，谢谢您，我理解了。想请问一下您训练11*11的棋盘就是用的dirichlet noise的参数为0.3吗，我之前在宋哥的代码里8*8的棋盘好像用的也是0.3，那11*11的棋盘是不是用小一点的好。有没有办法根据训练过程来看要调小还是调大这个参数。

**Comment by initial-h** [comment]
如果算力够的话，可以做实验对比一下效果。感觉取值只要不是太极端，这个参数应该不太敏感。

**Comment by 161220028jcdai** [comment]
好的，谢谢，我先训练一段时间看看收敛情况

**Comment by 161220028jcdai** [comment]
您好，关于这个参数我理解了，然后我研究了一下网络的结构，发现您和alphagozero论文里的网络结构有些不一样，我初学AI只学了keras就用keras重写了一下网络结构，能请您帮我看一下有没有问题吗，我是按照paper里的网络结构写的，但是训练不收敛，不知道哪里写错了。
```python
        # 输入层
        in_x = network = Input((4, self.board_width, self.board_height))

        # 输入模块处理
        network = Conv2D(filters=64, kernel_size=(3, 3), padding="same", data_format="channels_first",
                         kernel_regularizer=l2(self.l2_const))(network)
        network = BatchNormalization()(network)
        network = ReLU()(network)
        
        # 4个残差模块
        for i in range(4):
            temp = network
            network = Conv2D(filters=64, kernel_size=(3, 3), padding="same", data_format="channels_first",
                             kernel_regularizer=l2(self.l2_const))(network)
            network = BatchNormalization()(network)
            network = ReLU()(network)
            network = Conv2D(filters=64, kernel_size=(3, 3), padding="same", data_format="channels_first",
                             kernel_regularizer=l2(self.l2_const))(network)
            network = BatchNormalization()(network)
            network = Add()([temp, network])
            network = ReLU()(network)

        # 策略网络部分 action policy layers
        policy_net = Conv2D(filters=2, kernel_size=(1, 1), padding="same", data_format="channels_first",
                            kernel_regularizer=l2(self.l2_const))(network)
        policy_net = BatchNormalization()(policy_net)
        policy_net = ReLU()(policy_net)
        policy_net = Flatten()(policy_net)
        self.policy_net = Dense(self.board_width * self.board_height, activation="softmax",
                                kernel_regularizer=l2(self.l2_const))(policy_net)
        
        # 价值网络部分 state value layers
        value_net = Conv2D(filters=1, kernel_size=(1, 1), padding="same", data_format="channels_first",
                           kernel_regularizer=l2(self.l2_const))(network)
        value_net = BatchNormalization()(value_net)
        value_net = ReLU()(value_net)
        value_net = Flatten()(value_net)
        value_net = Dense(64, kernel_regularizer=l2(self.l2_const))(value_net)
        value_net = ReLU()(value_net)
        self.value_net = Dense(1, activation="tanh", kernel_regularizer=l2(self.l2_const))(value_net)

        # 创建网络
        self.model = Model(in_x, [self.policy_net, self.value_net])
```
paper里原本都是256个filters的，然后我训练的是10*10的棋盘而且五子棋比较简单就都改成了64，然后输入的特征平面简化成了4个（分别代表我方棋子位置、对手棋子位置、先手方、对手上一步落子位置）。不知道哪里写错了。另外dirichlet noise的alpha参数我改成了0.2

**Comment by 161220028jcdai** [comment]
我有用到GPU就没有把NCHW换成NHWC，我看见知乎上说用GPU的话NCHW更快

**Comment by 161220028jcdai** [comment]
![image](https://user-images.githubusercontent.com/42955715/82062016-0f400400-96fc-11ea-8547-c518781c9075.png)

我是在按这个图上的网络结构写的，减少了残差块的数量（19改为4）以及卷积核的数量（256改为64）

**Comment by initial-h** [comment]
没用过keras，网络看起来没问题，再检查一下训练部分吧，比如loss,optimizer,BN etc.可以找个分类数据集测一测，比如MNIST，这样比较快。
通道的问题tf的issue也有人问，具体没有尝试过，data_format选对了应该也不会出问题。
网络结构我也是这么写的，只是第一次做了一个1x1卷积，其他参数调一下应该也不影响。

**Comment by 161220028jcdai** [comment]
您好，我修改了一下训练部分以后训练了8000局（10x10的棋盘），发现这期间loss不稳定。
在训练至3500局左右的时候第一次降至2.1左右，然后训练几百局以后又突然升到2.3-2.5左右，又训练了几百局以后又降到2.1，再训练几百局又升至2.3、2.4左右，循环往复。。。请问loss升高是说明策略退化了吗，不知道怎么解决这个问题，应该在loss降至2.0-2.1的时候停止训练吗？
[entropy_10x10_mykeras.txt](https://github.com/initial-h/AlphaZero_Gomoku_MPI/files/4641997/entropy_10x10_mykeras.txt)
[loss_10x10_mykeras.txt](https://github.com/initial-h/AlphaZero_Gomoku_MPI/files/4642694/loss_10x10_mykeras.txt)

**Comment by initial-h** [comment]
loss有波动是正常的，可能是buffer 还没满，或者采样数据之间的差异有变化。可以算一下R²看看效果如何，也就是代码里那个explained variance，能够在0.6甚至更大，应该没啥问题。

**Comment by 161220028jcdai** [comment]
好的，谢谢您，我继续训练一下试试看。另外想问一下您11x11的模型训练的时候最终的loss收敛到了多少左右，想做个参考。
另外想请问一下kl散度这个值，最终的目标是应该越小越好吗。

**Comment by initial-h** [comment]
不太记得了，这个和很多因素都有关系，buffer大小，batch size，网络结构这些都会影响，参考价值不大。

**Comment by 161220028jcdai** [comment]
哦哦好的，kl散度这个值的最终目标是应该越小越好吗。

**Comment by initial-h** [comment]
kl是原来宋大佬的代码里用来调整学习率的，我多进程改成epoch的训练之后就没再用这个了。这里off-policy的方式做监督训练，个人感觉不太需要调整学习率。
KL主要是PG里面用来控制新旧策略的差异的，使得两个策略差异不要太大，增加采样效率，避免策略collapse，但是也不能完全相同，不然策略就没有改变了。所以也不能说越小越好，控制在比较小的程度就行。

**Comment by 161220028jcdai** [comment]
不好意思又打扰您了，想向你请教一下game_board.py中获取黑白双方历史4步的那块代码是什么意思。

```
         for i in range(self.feature_planes):

                # put all moves on planes

                if i%2 == 0:

                    square_state[i][move_oppo // self.width,move_oppo % self.height] = 1.0

                else:

                    square_state[i][move_curr // self.width,move_curr % self.height] = 1.0

            # delete some moves to construct the planes with history features

            for i in range(0,len(self.states_sequence)-2,2):

                for j in range(i+2,len(self.states_sequence),2):

                    if self.states_sequence[i][1]!= -1:

                        assert square_state[j][self.states_sequence[i][0] // self.width,self.states_sequence[i][0] % self.height] == 1.0, 'wrong oppo number'

                        square_state[j][self.states_sequence[i][0] // self.width, self.states_sequence[i][0] % self.height] = 0.

            for i in range(1,len(self.states_sequence)-2,2):

                for j in range(i+2,len(self.states_sequence),2):

                    if self.states_sequence[i][1] != -1:

                        assert square_state[j][self.states_sequence[i][0] // self.width,self.states_sequence[i][0] % self.height] ==1.0, 'wrong player number'

                        square_state[j][self.states_sequence[i][0] // self.width, self.states_sequence[i][0] % self.height] = 0.
```
我训练的时候只用了双方当前的局面没用历史棋局，效果不太好，想加上您这一块但没有理解这一部分代码的逻辑。这里的state_sequence的作用是什么，那两个for循环是按什么样的逻辑来得到历史局面的。（我感觉自己脑子太笨了）恳请您解释一下代码的逻辑，实在是麻烦您了！

**Comment by initial-h** [comment]
谢谢看的这么仔细，你会进步很快的。这里我是先建一个全为0的array，然后把当前玩家和对手的所有动作交叉放到对应的array上，然后依次在每个plane上删除该玩家上一次的动作形成一个状态序列。
