### ISSUE TITLE
Why not use np.flipud to do dihedral reflection?

### ISSUE THREAD

**Issue by leilani-x** [initial-h/AlphaZero_Gomoku_MPI#34]
Thanks for your implementation. I have the following questions:

https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L188-L189

Why not combine np.fliplr and np.flipud when flipping? Why only use np.fliplr?

**Comment by initial-h** [comment]
Hi, you are right, I did not use the both. Because I rotate the state first, and then fliplr it. This can achieve the same effect.
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L185-L189

**Comment by leilani-x** [comment]
> Hi, you are right, I did not use the both. Because I rotate the state first, and then fliplr it. This can achieve the same effect.
> https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/policy_value_net_tensorlayer.py#L185-L189

Thx, get it  👍
