### ISSUE TITLE
I have a question about entropy

### ISSUE THREAD

**Issue by 1331han** [initial-h/AlphaZero_Gomoku_MPI#35]
I understood that entropy is simply a means of monitoring and that well-trained models have small entropy. So is entropy the figure of the variance?

**Comment by initial-h** [comment]
hi, first the code is at here
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/policy_value_net_tensorlayer.py#L72-L74
And, I think they are different. Variance is a metric for a batch of samples, entropy is a metric for a distribution. And, if all samples is the same, variance=0, but if all probililties are same like uniform distribution, the entropy is maximum.
