### ISSUE TITLE
how to modify code to AI VS AI?

### ISSUE THREAD

**Issue by massawuyh** [initial-h/AlphaZero_Gomoku_MPI#36]
hi, I want to ask how to modify the code to realize AI VS AI?
Thanks!

**Comment by initial-h** [comment]
Hi, it has been here
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train_mpi.py#L201-L223

**Comment by massawuyh** [comment]
ok, thanks!
