### ISSUE TITLE
training for size of 19*19 and connect-six is so slow，what should I do？

### ISSUE THREAD

**Issue by 177715031** [initial-h/AlphaZero_Gomoku_MPI#37]

**Comment by initial-h** [comment]
Hi,
The problem you describe is still unclear. You'd better talk more about what you have done, like which script you run, what parameters you use, the configuration about your server/PC and concretely how slow about your training. 
Anyway, I just assume you only change gomoku into connect-six and there's no bug, you can try these
1) Enlarge your scalability using MPI version. Like I used on gomoku, mpiexec -np 43 python -u train_mpi.py. 43 here is the number of process and you can use a lager number.
2) Use transfer learning. Reload the model I trained for gomoku and train your connect-six based on the model.
3) Train a smaller size of connect-six first and then use transfer learning.
