### ISSUE TITLE
感谢作者，这是我用过最有用的架构，我修改成了keras的模型，我有一个问题，当训练到后期的时候，episode_len会越来越小，在9-15左右

### ISSUE THREAD

**Issue by yuan6785** [initial-h/AlphaZero_Gomoku_MPI#38]
这个项目我训练出来了，我修改成了keras的模型，我有一个问题，当训练到后期的时候，episode_len会越来越小，在9-15左右； 按我的理解，模型越到后期应该越优秀，自我对弈的步数应该越来越多，episode_len应该会越来越大才对，为什么会越来越小，而且效果也不差，我是比较费解这一点。     是因为first_n_moves的temp为1导致的吗？

**Comment by initial-h** [comment]
再接着训练应该会再变长。这个现象可以理解成，刚开始训练双方都乱走所以horizon很长；接着走得有点水平了，某一步走错就会被对方抓住机会，所以horizon就变短了；再往后双方都更强，就算前期因为随机性走了一步不太好的，后期也能弥补回来，所以horizon又会变长。
