### ISSUE TITLE
小白关于mpi多进程通信求助

### ISSUE THREAD

**Issue by ojbk888** [initial-h/AlphaZero_Gomoku_MPI#39]
作者您好，最近在学习您的项目，有个问题想不通，如果是要实现batch预测，怎样用mpi4py来实现缓冲队列并检测其中是否有新的元素呢，我尝试使用send和recv函数，发现recv不到东西进程会阻塞在那里，怎样才能实现接收不到东西就继续执行下面的代码呢？十分感谢

**Comment by initial-h** [comment]
sorry啊，我没有亲手做过，帮不上忙。不过应该是可以通过某种方式实现的，这个repo好像是并行的MCTS
https://github.com/hijkzzz/alpha-zero-gomoku

**Comment by ojbk888** [comment]
好的，十分感谢！
