### ISSUE TITLE
概率显示问题

### ISSUE THREAD

**Issue by liunian321** [initial-h/AlphaZero_Gomoku_MPI#4]
目前的概率显示是在命令行中打印概率，没有坐标很难认。
请问怎么改动。
顺便提点建议：能在弹出的面板显示AI认为所有合法落子点的概率吗？（每个落子点的概率大小由颜色深浅表示）。
十分感谢。

**Comment by initial-h** [comment]
概率只是简单打印出来了，想要修改可以在对应位置修改。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/ab69b180dc37ee7ccd5d266f893625f12bb0373f/mcts_alphaZero.py#L296-L305
也可以再写一个图形界面展示概率，这套代码主要关注的算法和训练，所以UI这块没有优化。
