### ISSUE TITLE
关于训练局数以及网络大小的疑问

### ISSUE THREAD

**Issue by ojbk888** [initial-h/AlphaZero_Gomoku_MPI#40]
作者您好，我想问一下您的15×15棋盘的模型的网络大小如何？大概训练了多少局？训练时的playout数设置为多少？如果想得到一个可以击败弈心的模型大概需要跑多少局？ 感谢您的回复。

**Comment by initial-h** [comment]
网络结构没有变化，参数也没有变化，局数没印象了。弈心是真的强，这个怕是需要训练量不少。

**Comment by initial-h** [comment]
之前有个类似的issue https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/10

**Comment by ojbk888** [comment]
好的，十分感谢
