### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by wiki-love** [initial-h/AlphaZero_Gomoku_MPI#43]
how long did it take you to train the 15*15 model ? the model seems well.

**Comment by initial-h** [comment]
issue [#10](https://github.com/initial-h/AlphaZero_Gomoku_MPI/issues/10)

**Comment by wiki-love** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wiki-love** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
