### ISSUE TITLE
laptop for this project

### ISSUE THREAD

**Issue by hharryyf** [initial-h/AlphaZero_Gomoku_MPI#44]
Hi, I saw you can run around 1e5 training games in 800h, but it would take me a year to run the same number of training games for a similar strategy game (connect-4) on my personal laptop. Could you please tell me your computer/laptop's brand and the OS for the machine?
Thanks.

**Comment by initial-h** [comment]
Hi, I can only remember the GPUs were two NVIDIA 1080Ti and I run 43 processes in parallel like
mpiexec -np 43 python -u train_mpi.py
