### ISSUE TITLE
转换成pytorch

### ISSUE THREAD

**Issue by ASL-zhenglu** [initial-h/AlphaZero_Gomoku_MPI#45]
作者你好，刚刚入门，我想问一下我想将你的tensorflow模型转换成pytorch，我需要学习哪些知识，目前已有tensorflow和pytorch部分基础，但还是很多地方看不懂，谢谢大佬

**Comment by initial-h** [comment]
可能搜一下tf和torch的模型保存和加载，应该有一些对应的关系

**Comment by initial-h** [comment]
这两issue有人做过一些模型转换，不是到torch的，不过可以交流一下经验
#16 
#38

**Comment by ASL-zhenglu** [comment]
谢谢大佬
