### ISSUE TITLE
关于experience replay的问题

### ISSUE THREAD

**Issue by Sunshine-718** [initial-h/AlphaZero_Gomoku_MPI#46]
你好，我了解到AlphaZero好像是一个on-policy算法，on-policy算法是不适用experience replay的，但是我又在代码里面看到使用了experience replay, 我想知道我的看法是不是对的。
https://github.com/initial-h/AlphaZero_Gomoku_MPI/blob/95867cb7e524ebe9c77a926c82091785693c3c0a/train.py#L122-L125

**Comment by initial-h** [comment]
是off-policy的

**Comment by Sunshine-718** [comment]
好的，谢谢大佬
