### ISSUE TITLE
把value head的输出改成像DQN一样的多头输出是否可行？

### ISSUE THREAD

**Issue by Sunshine-718** [initial-h/AlphaZero_Gomoku_MPI#47]
经过模仿您的框架，我的实验已经取得一些成功，非常感谢
我有以下几点设想，想跟您讨论一下：

把value head的输出层改成像DQN一样，改完后计算value有以下几个方案：
1. 每个节点的value从Q网络产生的多个Q中取最大值
2. 每个节点的value=policy head输出的概率加权每个Q求和
3. 每个节点的value=policy head输出的最大概率对应的动作，由这个动作取得对应的Q值

更进一步地，取消policy head，动作概率由多个子节点Q值经过softmax得到概率

**Comment by initial-h** [comment]
这样改进是出于什么考虑呢？

**Comment by Sunshine-718** [comment]
这样是否可以更好地反映每个节点的动作价值？或者说能获取更详细的信息

**Comment by initial-h** [comment]
感觉不好判断，只能做实验看效果了
