### ISSUE TITLE
C_puct 参数

### ISSUE THREAD

**Issue by Sunshine-718** [initial-h/AlphaZero_Gomoku_MPI#48]
对于C_puct参数我有一个疑问，我查过原论文还有网上的一些资料，我没发现原论文C_puct参数的具体设置，在您的README文档里提到原论文的C_puct参数是5。
此外，我也看了其他的repo，C_puct的设置是1.5或1，请问作者您有尝试过其他C_puct参数吗？5是否是最优的？

**Comment by initial-h** [comment]
AlphaGo的论文里设置的5，这里直接沿用了
