### ISSUE TITLE
AI执黑不走天元

### ISSUE THREAD

**Issue by Augustusmyc** [initial-h/AlphaZero_Gomoku_MPI#6]
我训练13 x 13的棋盘，即使过了很久，AI执黑棋第一步依然不走中间，概率输出如下：
value [[0.80382586]]
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0 0.233   0.0   0.0   0.0 0.256   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0 0.236   0.0   0.0   0.0 0.276   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

我把模型调小，并把噪声调低了一点（见后文），问题依旧，请问你知道是怎么回事吗？
调低噪音的代码：
`dirichlet_noise = np.random.dirichlet(0.25 * np.ones(length)) # 原来是0.3`
`self._children[action_priors[i][0]] = TreeNode(self,0.8*action_priors[i][1]+0.2*dirichlet_noise[i]) #原来是0.75/0.25`

**Comment by initial-h** [comment]
你训练了多少局，是多进程并行的还是单进程的

**Comment by Augustusmyc** [comment]
多进程，在服务器上跑的，目前的最后输出如下：
current policy model loaded! rank:3,game batch num :5498
now time : 90.2333643134435
rank : 3, restore model time : 0.020583222773340012, collect_data_time : 90.1980754325125, save_data_time : 0.01433751536740197

应该是有几千局了吧，我隔一段时间就把当前最好的模型下载下来看，从很早的某个模型开始就一直是这样，AI执黑第一步不走天元。
感觉目前的模型棋力还行，就是第一步不走天元这一点让我很郁闷。

**Comment by initial-h** [comment]
这个问题我也遇到过，特别是大棋盘的情况下。我猜测可能是因为五子棋这个游戏先手第一步很重要，再加上棋谱普遍偏短，如果网络在学习的过程中发现偏离中心点的先手也可以赢，那就很难再去探索中心点了。特别是算力有限，训练次数较少的情况下。
要改善这个问题，可以加大探索度，同时训练更长时间。如果算力有限又希望先手走中心位置，可以调整一下噪声，人为地让它更大概率选择中心点。

**Comment by Augustusmyc** [comment]
明白了，非常感谢。
如果可以的话，能否透露一下，你训练的15x15的模型用了几块Nvidia显卡，开了多少个进程，训练了大约多长时间（或者说多少局）？

**Comment by initial-h** [comment]
15x15的配置和之前11x11的是一样的，区别只是把dirichlet噪声参数调小了。
训练这个模型的时候中途停了很多次，并没有专门统计数据。可能时间上不超过一个月应该，棋力也还比较弱。
