### ISSUE TITLE
基于您提供的model再进行训练问题

### ISSUE THREAD

**Issue by liunian321** [initial-h/AlphaZero_Gomoku_MPI#7]
基于您提供的model训练，发现跑偏了？从一个高手立马变成了一个菜鸟。。
请问这种情况怎么办？
学习率是2e-3,play_out是200，first_moves是1
顺便感谢您的付出。

**Comment by initial-h** [comment]
还有更多信息吗？比如多大的棋盘，单进程训练还是多进程，收集了多少数据。

**Comment by liunian321** [comment]
> 还有更多信息吗？比如多大的棋盘，单进程训练还是多进程，收集了多少数据。

15x15的棋盘，单线程，可能只下了一百多盘的样子。

**Comment by initial-h** [comment]
单进程很慢，而且下的局数太少。如果是加载模型继续训练，建议先多收集棋谱再训练网络，比如先把buffer填满。
