### ISSUE TITLE
关于MPI版的显卡利用率

### ISSUE THREAD

**Issue by hijkzzz** [initial-h/AlphaZero_Gomoku_MPI#8]
出于兴趣我也写了一个单机并行的C++版AlphaZero
训练了12个小时 15*15棋盘 3500局(MCTS 1600次搜索+单块 GTX1070) 
测试发现棋力还不错，预计完全训练可能要几天乃至一周
https://github.com/hijkzzz/alpha-zero-gomoku

看到这个MPI版的特别感兴趣，稍微研究了一下原理
但想问一下MPI这种多进程版本的，GPU的利用率能达到多少，还有就是显存会不会吃的很紧
因为根据我的测试，AlphaZero的主要瓶颈是MCTS中用神经网络预测那一步，GPU利用率上不来的话实际效率很难提升。

**Comment by initial-h** [comment]
具体可以根据自己的硬件调整，我两块卡显存基本占满，利用率一块100%一块70-80%，还算比较高了。
另外，注意到你单卡12小时可以下3500局而且搜1600次，不知道是C++比较快还是网络结构深度的原因？

**Comment by hijkzzz** [comment]
> 具体可以根据自己的硬件调整，我两块卡显存基本占满，利用率一块100%一块70-80%，还算比较高了。
> 另外，注意到你单卡12小时可以下3500局而且搜1600次，不知道是C++比较快还是网络结构深度的原因？

网络深度是4层ResNet，不过我测试的时候每棵树用8个线程并行，然后同时运行10局以上自对弈，预测以及搜索都是用C++实现的。我的方式是只维护一个神经网络，用缓冲队列cat每个线程的预测提高显存和GPU利用率的。
因为PyTorch默认使用Default CUDA Stream与显卡进行I/O，相当于同时只能单线程调用CUDA，开启多个线程无法提高利用率。
你这个占用率挺高的，我猜可能是TensorFlow底层为每个进程分配不同的CUDA Stream，所以可以多进程调用CUDA。具体有待研究~

**Comment by initial-h** [comment]
那可能是我的网络结构更深，所以慢了许多。一棵树用8个线程，那相当于是写了一个异步树搜索？不知道8个线程去做和搜索次数x8哪个效果更好？
占用率可能是线程和进程的区别吧，我的每个进程都维护一个网络，很吃显存，同时进程之间调用显卡资源是没有交互的。具体涉及到底层cuda的实现就不了解了。

**Comment by hijkzzz** [comment]
异步树搜索实际对弈的时候很有优势，比如可以开16个线程6400次搜索，用时和400次搜索差不多的（效果一定程度差于单线程6400次）。所以我才跑了3500局，电脑先手自己就不一定下的过了（另外就是训练的时候搜索越深，收敛越快）。有时间我再整合MPI弄一个多机分布式的版本看看，不过一局对弈一个神经网络，这种方法弊端很多，首先很吃显存，其次显卡实际利用率不高，因为单样本预测效率不如batch预测。

**Comment by initial-h** [comment]
确实是，不过batch输入的话，中间有等待吗？是不间断flush队列还是每隔一段时间flush一下呢？还有就是不知道异步树搜索这边是怎么实现的呢，virtual lock怎么设置的呢，感谢。

**Comment by hijkzzz** [comment]
可以设置为等待1ms没有新数据就flush。virtual loss的话这个很主观的，主要就是线程访问到这个节点就减去一定价值。实现你可以看看我的项目src/mcts.cpp那个文件，和python的实现略有区别。我稍微考虑了一下，结合MPI进程通信，设置两个节点用于队列预测，其他节点跑样本，这样应该可以有不错的扩展性。
