### ISSUE TITLE
我用多进程训练的时候GPU和CPU都没有在使用

### ISSUE THREAD

**Issue by REFunction** [initial-h/AlphaZero_Gomoku_MPI#9]
我把np设置成了8和4都是这样的，CPU使用率0.3%，GPU使用率0%，界面卡在epoch 0上了

**Comment by initial-h** [comment]
还有其他详细信息吗？比如代码是否改动，MPI，cuda和cudnn的配置等等。

**Comment by REFunction** [comment]
首先值得一提的是train.py改成15x15可以正常运行，GPU使用率不为0
在train_mpi.py里，我把11x11也改成了15x15
mpi安装的是openmpi，用apt安装的，mpiexec可以执行（否则也不会出现使用率的问题）

openmpi信息
libopenmpi1.10/xenial,now 1.10.2-8ubuntu1 amd64 [installed,automatic]
openmpi-bin/xenial,now 1.10.2-8ubuntu1 amd64 [installed]
openmpi-common/xenial,xenial,now 1.10.2-8ubuntu1 all [installed,automatic]

显卡信息
驱动410.78 cuda 10.0 cudnn 7.4.2 python 3.6.7

**Comment by initial-h** [comment]
cuda和cudnn应该没问题，mpiexec不报错吗，能不能大概看出卡在哪一行代码了。有没有试试mpi测试代码能不能运行，或者贴一下终端的详细信息。
